name: Run Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          
      - name: Install Poetry
        run: pip install poetry
          
      - name: Install dependencies
        run: poetry install --no-root --no-interaction

      - name: Set required environment variables
        run: |
          CURRENT_DATETIME=$(date +"%Y%m%d_%H%M%S")
          echo "CURRENT_DATETIME=${CURRENT_DATETIME}" >> "$GITHUB_ENV"

          OUTPUT_FILE="listings_${CURRENT_DATETIME}.json"
          echo "OUTPUT_FILE=${OUTPUT_FILE}" >> "$GITHUB_ENV"

      - name: Run scraper
        run: .github/scripts/run.sh

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.PAT_SCRAPE_CENTRIS }}
        run: |
          gh release create "listings-${CURRENT_DATETIME}" \
            --generate-notes \
            --notes "Listings scraped on ${CURRENT_DATETIME}" \
            "${OUTPUT_FILE}"
