name: Run Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  pull_request:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  scrape:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/813050693418/locations/global/workloadIdentityPools/github-actions-scrape-centris/providers/github'
          service_account: 'scrape-centris@dfrancoeur.iam.gserviceaccount.com'

      - name: Set required environment variables
        run: |
          CURRENT_DATETIME=$(date +"%Y%m%d_%H%M%S")
          echo "CURRENT_DATETIME=${CURRENT_DATETIME}" >> "$GITHUB_ENV"

          OUTPUT_FILE="listings_${CURRENT_DATETIME}.json"
          echo "OUTPUT_FILE=${OUTPUT_FILE}" >> "$GITHUB_ENV"

          DB_NAME="scrape-centris.db"
          echo "DB_NAME=${DB_NAME}" >> "$GITHUB_ENV"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Download database
        run: |
          gcloud storage cp "gs://${{ secrets.GCS_BUCKET_SCRAPE_CENTRIS }}/${DB_NAME}" ./${DB_NAME}
          
      - name: Install Poetry
        run: pip install poetry
          
      - name: Install dependencies
        run: poetry install --no-root --no-interaction

      - name: Run scraper
        run: .github/scripts/run.sh "./${OUTPUT_FILE}"

      - name: Add result to database
        run: .github/scripts/indb.sh "./${DB_NAME}" "./${OUTPUT_FILE}"

      - name: Upload database
        run: |
          gcloud storage cp ./${DB_NAME} "gs://${{ secrets.GCS_BUCKET_SCRAPE_CENTRIS }}/${DB_NAME}"
