name: Run Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          
      - name: Install Poetry
        run: pip install poetry
          
      - name: Install dependencies
        run: poetry install --no-root --no-interaction

      - name: Run scraper
        run: .github/scripts/run.sh

      - name: Upload scraped data
        uses: actions/upload-artifact@v4
        with:
          name: scraped-listings
          path: ${{ env.OUTPUT_FILE }}
